env:
  token: ${{ secrets.TOKEN }}

name: create-map
on: push
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Configure Git
      run: |
        git config --global user.email "tushar.sao@ext.soprabanking.com"
        git config --global user.name "tusharsao"
      shell: bash
    - name: Run script file
      run: |
        chmod +x ./contributions.sh
        ./contributions.sh
      shell: bash
