env:
  token: ${{ secrets.TOKEN }}

name: create-map
on: push
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Configure Git
      run: |
        git config --global user.email "tusharsao25@gmail.com"
        git config --global user.name "Tushar-2510"
      shell: bash
    - name: Run script file
      run: |
        chmod +x ./contributions.sh
        ./contributions.sh
      shell: bash
    - name: commit changes
      run: |
          git add .
          git commit -m "Commit message from GitHub Actions"
          git push
