env:
  token: ${{ secrets.TOKEN }}

name: create-map
on: push
permissions:
  actions: read|write|none
  checks: read|write|none
  contents: read|write|none
  deployments: read|write|none
  id-token: read|write|none
  issues: read|write|none
  discussions: read|write|none
  packages: read|write|none
  pages: read|write|none
  pull-requests: read|write|none
  repository-projects: read|write|none
  security-events: read|write|none
  statuses: read|write|none
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Configure Git
      run: |
        git config --global user.email "tusharsao25@gmail.com"
        git config --global user.name "Tushar-2510"
      shell: bash
    - name: Run script file
      run: |
        chmod +x ./contributions.sh
        ./contributions.sh
      shell: bash
    - name: commit changes
      run: |
          git config --global user.email "tusharsao25@gmail.com"
          git config --global user.name "Tushar-2510"
          git add .
          git commit -m "Commit message from GitHub Actions"
          git push
